stages:
  - deploy

pages:
  image: ghcr.io/astral-sh/uv:python3.11-bookworm-slim
  stage: deploy
  before_script:
    - uv sync --locked
  script:
    - uv run mkdocs build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
