stages:
  - deploy

pages:
  image: python:3.11
  stage: deploy
  before_script:
    - pip install mkdocs-material
  script:
    - mkdocs build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
