site_name: configr-cli
site_url: https://edgar-treischl.github.io/configr-cli/
repo_url: https://github.com/edgar-treischl/configr-cli
repo_name: edgar-treischl/configr-cli
site_author: Edgar Treischl
site_dir: public

theme:
  name: material
  icon: 
    repo: fontawesome/brands/github
  logo: images/logo.png
  palette:
    - scheme: default
      primary: black
      accent: black
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono

  # Navbar customization for right side links with icons
  features:
    - navigation.top
    - navigation.tabs
    - navigation.footer 
    - content.code.copy

nav:
  - Home: index.md
  - Get Started: getstarted.md