[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "configr-cli"
version = "0.2.1"
description = "CLI tool to fetch shared config files from GitLab"
authors = [{ name="Edgar Treischl", email="edgar.treischl@bayern.isb.de" }]
readme = "README.md"
license = { text = "MIT" }
keywords = ["cli", "gitlab", "config", "automation"]
requires-python = ">=3.11"
dependencies = [
    "click",
    "requests",
    "InquirerPy",
    "pyperclip",
    "python-dotenv",
    "textual>=8.0.0",
    "rich>=13.0.0",
    "great-docs>=0.17.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black",
    "ruff",
    "pre-commit",
]

[project.scripts]
configr = "configr_cli.cli:cli"

[dependency-groups]
dev = [
    "pytest>=7.0",
    "black",
    "ruff",
    "pre-commit",
]
